login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.LoginView.as_view(), name='Login'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('list/', views.save, name='save'),
]

thientube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('menu.urls')),
    path('', include('login.urls'))
]

login/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

menu/models.py
from django.db import models

# Create your models here.


class ListVideo(models.Model):
    url = models.CharField(max_length=1000)
    image = models.CharField(max_length=1000)
    content = models.CharField(max_length=100)
    creator = models.CharField(max_length=30)

login/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

menu/forms.py
from django import forms
from .models import ListVideo


class ListVideoForm(forms.ModelForm):
    class Meta:
        model = ListVideo
        fields = ('url', 'image', 'content', 'creator')

login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from .models import User
from .forms import UserForm
from django.contrib.auth import authenticate, login

# Create your views here.


class LoginView(View):
    def get(self, request):
        return render(request, 'login/login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        my_user = authenticate(username=username, password=password)
        if my_user is not None:
            # login(request, my_user)
            return HttpResponseRedirect("/home/")

        return HttpResponse("401 Not Authorized")

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ListVideoForm
from .models import ListVideo
from django.contrib.auth import decorators

# Create your views here.


# @decorators.login_required()
def home(request):
    video = ListVideo.objects.all()
    return render(request, 'menus/home.html', {"video": video})


# @decorators.login_required()
def create(request):
    video = ListVideoForm()
    return render(request, 'menus/create.html', {"v": video})


# @decorators.login_required()
def save(request):
    if request.method == "POST":
        v = ListVideoForm(request.POST)
        if v.is_valid():
            v.save()
            # video = ListVideo.objects.all()
            return HttpResponseRedirect('/home/')
        else:
            return HttpResponse("Save False")
    else:
        return HttpResponse("Not Method POST")

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <style>
        
            body {
                font-family: Arial, Helvetica, sans-serif;
                background-image: url(https://img5.thuthuatphanmem.vn/uploads/2021/08/25/background-3d-4k_085529380.jpg);
            }
            
            input[type=text], input[type=password] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            box-sizing: border-box;
            }
            
            button {
            background-color: #04AA6D;
            color: white;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            }

            button:hover {
            opacity: 0.8;
            }

            /* Extra styles for the cancel button */
            .cancelbtn {
            width: auto;
            padding: 10px 18px;
            background-color: #f44336;
            }

            /* Center the image and position the close button */
            .imgcontainer {
            text-align: center;
            margin: 24px 0 12px 0;
            position: relative;
            }

            img.avatar {
            width: 40%;
            border-radius: 50%;
            }

            .container {
            padding: 16px;
            }

            span.psw {
            float: right;
            padding-top: 16px;
            }

            /* The Modal (background) */
            .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            padding-top: 60px;
            }

            /* Modal Content/Box */
            .modal-content {
            background-color: #fefefe;
            margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
            border: 1px solid #888;
            width: 80%; /* Could be more or less, depending on screen size */
            }

            /* The Close Button (x) */
            .close {
            position: absolute;
            right: 25px;
            top: 0;
            color: #000;
            font-size: 35px;
            font-weight: bold;
            }

            .close:hover,
            .close:focus {
            color: red;
            cursor: pointer;
            }

            /* Add Zoom Animation */
            .animate {
            -webkit-animation: animatezoom 0.6s;
            animation: animatezoom 0.6s
            }

            @-webkit-keyframes animatezoom {
            from {-webkit-transform: scale(0)} 
            to {-webkit-transform: scale(1)}
            }
            
            @keyframes animatezoom {
            from {transform: scale(0)} 
            to {transform: scale(1)}
            }

            /* Change styles for span and cancel button on extra small screens */
            @media screen and (max-width: 300px) {
            span.psw {
                display: block;
                float: none;
            }
            .cancelbtn {
                width: 100%;
            }
        }
    </style>


</head>
<body>

    <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

    <div id="id01" class="modal">
    
    <form class="modal-content animate" form method="POST">
        {% csrf_token %}
        <div class="imgcontainer">
        <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
        <img src="https://img5.thuthuatphanmem.vn/uploads/2021/08/25/background-3d-4k_085529380.jpg" alt="Avatar" class="avatar">
        </div>

        <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required>
            
        <button type="submit">Login</button>
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
        </div>

        <div class="container" style="background-color:#f1f1f1">
        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
        <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
    </form>
    </div>

    <script>
    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    </script>


</body>
</html>

menu/templates/menus/create.html
{% extends 'menus/home.html' %}
{% block create %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-image: url(https://img5.thuthuatphanmem.vn/uploads/2021/08/25/background-3d-4k_085529380.jpg);
        }

        * {
            box-sizing: border-box;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            margin-top: 6px;
            margin-bottom: 16px;
            resize: vertical;
        }

        input[type=submit] {
            background-color: #04AA6D;
            color: white;
            padding: 12px 20px;
            border: none;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        .containers {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 10px;
        }

        .column {
            float: left;
            width: 50%;
            margin-top: 6px;
            padding: 20px;
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        @media screen and (max-width: 600px) {
            .column, input[type=submit] {
                width: 100%;
                margin-top: 0;
            }
        }

    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Video</title>
</head>
<body>
    {% comment %} <form action="{% url 'menu:save' %}" method="post">
        {% csrf_token %}
        <h4>Url video</h4>
        {{v.url}}
        <h4>Image</h4>{{v.image}}
        <h4>Content</h4>
        {{v.content}}
        <h4>Creator</h4>
        {{v.creator}}
        <br>
        <button type="submit">Create Video</button>
    </form> {% endcomment %}

    <div class="containers">
    <div style="text-align:center">
        <h2>Create Video</h2>
    </div>
    <div class="row">
        <div class="column">
        <img src="https://mondaycareer.com/wp-content/uploads/2020/11/background-%C4%91%E1%BA%B9p-3-1024x682.jpg" style="width:100%">
        </div>
        <div class="column">
        <form action="{% url 'menu:save' %}" method="post">
            {% csrf_token %}
            <label for="fname">Url video</label>
                {{v.url}}
            <label for="lname">Image</label>
                {{v.image}}
            <label for="country">Content</label>
                {{v.content}}
            <label for="subject">Creator</label>
                {{v.creator}}
            <input type="submit" value="Create Video">
        </form>
        </div>
    </div>
    </div>


</body>
</html>
{% endblock %}

menu/templates/menus/save.html
{% extends 'menus/home.html' %}
{% block list %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Save Video</title>
</head>
<body>
    <div class="listvideo">
        {% if video %}
        {% for item in video%}
            <a class="listvideo-a" href="{{item.url}}">
                <form class="listvideo-form">
                    <div class="img">
                        <img class="listvideo-img" src="{{item.image}}" />
                    </div>
                    <div class="listvideo-content">
                        <h3>{{item.content}}</h3>
                        <p>{{item.creator}}</p>
                    </div>
                </form>
            </a>
            <br>
            {% endfor %}
        {% endif %}
    </div>
</body>
</html>
{% endblock %}